version: "3"

services:
  api:
    image: media-srv:latest
    depends_on:
      - db
    ports:
      - "8080:${API_PORT?err}"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD?err}
      POSTGRES_USER: ${DB_USERNAME?err}
      POSTGRES_DB: ${DB_DATABASE?err}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database_data:
