// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"time"

	"github.com/google/uuid"
)

type OriginalItem struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	URL       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}

type ResizedItem struct {
	ID        uuid.UUID `json:"id"`
	OID       uuid.UUID `json:"oid"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	URL       string    `json:"url"`
	Height    int32     `json:"height"`
	Width     int32     `json:"width"`
	CreatedAt time.Time `json:"created_at"`
}
